module.exports = {
  env: {
    SHOPIFY_STOREFRONT_ACCESS_TOKEN: process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN,
    SHOPIFY_STORE_DOMAIN: process.env.SHOPIFY_STORE_DOMAIN,
    NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN: process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN,
    NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN: process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN,
    NEXT_PUBLIC_MORALIS_SERVER_URL: process.env.NEXT_PUBLIC_MORALIS_SERVER_URL,
    NEXT_PUBLIC_MORALIS_APPID: process.env.NEXT_PUBLIC_MORALIS_APPID,
    MORALIS_SERVER_URL: process.env.MORALIS_SERVER_URL,
    MORALIS_APPID: process.env.MORALIS_APPID

  },
  images: {
    domains: ['cdn.shopify.com']
  }
}
